### PR TITLE
Colorize JSON output displayed with termbox

### PR DESCRIPTION
**Pull request by nwidger**
This commit uses the jsoncolor package and a custom termboxSprintfFuncer
type to make jid print out colorized JSON output.  The colors were
chosen to match those of jq's.

### CODE REVIEW

**Comment by simeji** [comment]
@nwidger Thanks for your great work! 

BTW, I have 2 questions.

1.  Dose [jsoncolor](https://github.com/nwidger/jsoncolor) have test_codes?

2.  Seemingly,  [jsoncolor LICENSE](https://github.com/nwidger/jsoncolor/blob/master/LICENSE) is GNU GPL v2. But `jid` is MIT LICENSE. Cloud you change jsoncolor's license?

**Comment by nwidger** [comment]
The jsoncolor package does not have any tests written for it yet.  I would welcome any contributions that add them, though.

I just changed jsoncolor's license to be MIT.

**Comment by simeji** [comment]
> I just changed jsoncolor's license to be MIT.
Thanks :)

..and I found a bug. (this PR)

```
echo '{"aa":"2AA2","bb":{"aaa":[123,"cccc",[1,2]],"c":321}}'| ./jid
```
and  `Ctrl+L`

then, it cause panic.

```
panic: invalid character 'a' looking for beginning of value
goroutine 1 [running]:
....
```
Could your fix it?

**Comment by nwidger** [comment]
Sure, I'll take a look at that.

**Comment by simeji** [comment]
@nwidger Thanks for fix the bug.

But, I found another bug.

It's caused When the JSON include Japanese characters (multibyte characters).
```
echo '{"aa":"北海道","bb":{"日本":"夏"}}'| ./jid
```
We can view the following JSON.
```
[Filter]> .
{
  "aa": "北道,
  "bb": {
    "日": "夏
  }
}
```
The behavior of jid version  0.6.1 is the following.
```
[Filter]> .
{
  "aa": "北 海 道 ",
  "bb": {
    "日 本 ": "夏 "
  }
}
```

**Comment by nwidger** [comment]
Nice catch, I'll look at this.

**Comment by simeji** [comment]
I think the approach of https://github.com/simeji/jid/pull/43/commits/eda880bd2ddd5fe0986061bf3daee8087d082cc1 is not good.
You should use the struct named`TerminalDrawAttributes`.

The jsoncolor only use to colorize jsons.
So when the jsoncolor processing is failed, the JSON is outputted without color.
It means we don't have the conditional branche of `drawCells` or `drawln`.

Additionally,  I didn't get correct behaviors of the jsoncolor (fg. What causes an error?), because It don't have test codes.

**Comment by nwidger** [comment]
I think it would be helpful if you gave a little more detail about what you think is the correct approach.  What do you envision the `TerminalDrawAttributes` struct containing and how should it be used?  How do you see `draw`, `drawln` and `drawCells` interacting?  What aspects of the current approach do you have issues with?

Internally, `jsoncolor` uses a `encoding/json` to parse the JSON into tokens.  The only instances where `jsoncolor` might fail is if `json.Marshal` or `json.Decoder.Token` return an error.  It should therefore be able to colorize any JSON document that `encoding/json` is able to handle.  Do you have an example of a JSON document that `jid` 0.6.1 is able to display but which `jsoncolor` fails on?

**Comment by nwidger** [comment]
@simeji Any update on this?  I'm happy to make changes that will get this merged.

**Comment by simeji** [comment]
@nwidger 
Sorry to keep you waiting. I'll take a action in few days.

**Comment by nwidger** [comment]
Sounds good!

**Comment by simeji** [comment]
@nwidger I want to some change it. So could you PR to [v0.7.0](https://github.com/simeji/jid/tree/v0.7.0)?

**Comment by nwidger** [comment]
@simeji I switched this PR to base off `v0.7.0`, hope that works for you.

**Comment by simeji** [comment]
@nwidger thank you!! :)

**Pull request merged**
